#!/usr/bin/env python

import sys, os
import json

import config
from muzi import muzi

configuration = config.config()
session = muzi.Muzi(configuration)

def write_playlist(playlist):

    sys.stdout.write("Select a playlist to download !!\n")
    i = 0
    for play in playlist['playlists']:
        sys.stdout.write(str(i)+". ")
        sys.stdout.write(play['name']+'\n')
        i += 1


def main():
    s = session.login()
    playlist = session.playlist_extractor()
    playlist = json.loads(playlist)

    write_playlist(playlist)
    num = raw_input()

    folder_name = playlist['playlists'][int(num)]['name']
    folder_name1 = folder_name.replace(' ', '\ ')

    if not os.path.exists("./"+str(folder_name1)):
        os.system("mkdir "+folder_name1)

    session.songs_extractor(num)
    session.song_downloader(folder_name)

    session.logout()


if __name__ == '__main__':
    main()
